server:
  port: 8763

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-hi2
  datasource:
   url: jdbc:mysql://localhost:3306/happy?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
   username: root
   password: 123
   driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: mapping/*.xml
